In [1]:
from opt_einsum import contract # idk why but its required to avoid bug in contract with numpy arrays
import torch
import numpy as np
from tqdm.auto import tqdm
torch.set_default_tensor_type(torch.cuda.DoubleTensor)
device=torch.device('cuda:0')
torch.cuda.set_device(device)


In [2]:
from TNModels import AKLT3D
# import importlib;import HOTRG;importlib.reload(HOTRG)
from HOTRG import HOTRG_layers,forward_observalbe_tensor_moments,trace_tensor,trace_two_tensors,forward_observable_tensor

In [5]:
params=AKLT3D.get_default_params()
params['a1']+=.008
print(params['a1'])
T0=AKLT3D(params).get_T0()
layers,Ts,logTotals=HOTRG_layers(T0,max_dim=10,nLayers=15,options={'mcf_enabled':True,'gilt_enabled':False,'mcf_fix_unitary_enabled':True})
_=[trace_two_tensors(T).item() for T in Ts]
print(_)


Y0,checkerboard=AKLT3D(params).get_observable('magnetizationZ')
_,T_ops,_=forward_observable_tensor(T0,Y0,layers,checkerboard=checkerboard,return_layers=True,cached_Ts=Ts)
_=[(trace_two_tensors(T_op).item(),trace_two_tensors(T).item()) for T_op,T in zip(T_ops,Ts)]
print([(_[0]/_[1] if _[1]!=0 else 0) for _ in _])


Y0,checkerboard=AKLT3D(params).get_observable('magnetizationX')
_,T_ops,_=forward_observable_tensor(T0,Y0,layers,checkerboard=checkerboard,return_layers=True,cached_Ts=Ts)
_=[(trace_two_tensors(T_op).item(),trace_two_tensors(T).item()) for T_op,T in zip(T_ops,Ts)]
print([(_[0]/_[1] if _[1]!=0 else 0) for _ in _])

Y0,checkerboard=AKLT3D(params).get_observable('magnetizationY')
_,T_ops,_=forward_observable_tensor(T0,Y0,layers,checkerboard=checkerboard,return_layers=True,cached_Ts=Ts)
_=[(trace_two_tensors(T_op).item(),trace_two_tensors(T).item()) for T_op,T in zip(T_ops,Ts)]
print([(_[0]/_[1] if _[1]!=0 else 0) for _ in _])

1.1627005383792515
Generating HOTRG layers


  0%|          | 0/15 [00:00<?, ?it/s]

HOTRG layers generated
[1.1757127162748148e-31, 0.013637626092916095, 1200.4883229832249, 8.182627603754408, 0.002711279605787548, 0.0018796731134640469, 0.002190360770507185, 0.0024802105339906356, 0.005352490447167672, 0.010953151607855427, 0.014365559574548704, 0.015065936302095337, 0.015326329495034317, 0.015445843447888468, 0.015522879016052565, 0.015588111213532135]


0it [00:00, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

[0.0, -2.7816750906607384, -1.8323450388345313, 1.4030229123179847, 1.058915832696755, 0.9454726018746118, 0.9108797878334939, 1.1545698191340557, 1.2887791442328502, 1.305081520473548, 1.3078686989178105, 1.3082236243830312, 1.3082796389404567, 1.3082976177245276, 1.3083023579608049, 1.3083035788290183]


0it [00:00, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

[-61.70550317655643, -0.3253717623568152, 3.4665263019277553e-09, -4.902551422269523e-07, 1.1281341079606244e-13, 5.662639267019688e-10, -1.1587411948523574e-12, -1.2208029732042913e-13, 2.3381554862465287e-11, 1.8942629893560502e-14, 2.966150020427627e-14, 1.4071376827784982e-12, 2.3453290197622624e-14, 2.4017364139532805e-14, 6.712658772171603e-14, 2.3702582519559735e-14]


0it [00:00, ?it/s]

  0%|          | 0/15 [00:00<?, ?it/s]

[61.70550317655641, 0.3367683382676732, -1.9295984096051186e-07, 1.1102885455659335e-06, 6.472273873823648e-12, -2.520497619113499e-10, 1.3102762063718267e-11, 1.2199916015272637e-11, 7.839857842499654e-12, 1.1265432820234837e-11, 1.1221975722536852e-11, 1.1219732653626386e-11, 1.1220955674529978e-11, 1.1219225918629282e-11, 1.1219193944654427e-11, 1.1219236404116141e-11]


In [ ]:


params=AKLT3D.get_default_params()
params['a1']+=.008
print(params['a1'])
T0=AKLT3D(params).get_T0()
layers,Ts,logTotals=HOTRG_layers(T0,max_dim=10,nLayers=15,options={'mcf_enabled':True,'gilt_enabled':False,'mcf_fix_unitary_enabled':True})
_=[trace_two_tensors(T).item() for T in Ts]
print(_)

Y0,checkerboard=AKLT3D(params).get_observable('magnetizationZ')
T_op_momentss,logTotals=forward_observalbe_tensor_moments([T0,Y0],layers,checkerboard=checkerboard,return_layers=True,cached_Ts=Ts)
_=[(trace_two_tensors(Y).item(),trace_two_tensors(T).item()) for T,Y in T_op_momentss[:]]
print([(_[0]/_[1] if _[1]!=0 else 0) for _ in _])

Y0,checkerboard=AKLT3D(params).get_observable('magnetizationX')
T_op_momentss,logTotals=forward_observalbe_tensor_moments([T0,Y0],layers,checkerboard=checkerboard,return_layers=True,cached_Ts=Ts)
_=[(trace_two_tensors(Y).item(),trace_two_tensors(T).item()) for T,Y in T_op_momentss[:]]
print([(_[0]/_[1] if _[1]!=0 else 0) for _ in _])

Y0,checkerboard=AKLT3D(params).get_observable('magnetizationY')
T_op_momentss,logTotals=forward_observalbe_tensor_moments([T0,Y0],layers,checkerboard=checkerboard,return_layers=True,cached_Ts=Ts)
_=[(trace_two_tensors(Y).item(),trace_two_tensors(T).item()) for T,Y in T_op_momentss[:]]
print([(_[0]/_[1] if _[1]!=0 else 0) for _ in _])

In [3]:
import importlib;import transfer_matrix;importlib.reload(transfer_matrix)
from transfer_matrix import get_scdims,get_transfer_matrix_operator
# 

In [ ]:
from TNModels import AKLT3D
import importlib;import HOTRG;importlib.reload(HOTRG)
from HOTRG import HOTRG_layers,forward_observalbe_tensor_moments,trace_tensor,trace_two_tensors

params=AKLT3D.get_default_params()
params['a1']+=.008
params['a1']
T0=AKLT3D(params).get_T0()
layers,Ts,logTotals=HOTRG_layers(T0,max_dim=10,nLayers=15,options={'mcf_enabled':False,'gilt_enabled':False,'mcf_fix_unitary_enabled':False})
Y0,checkerboard=AKLT3D(params).get_observable('magnetizationZ')
T_op_momentss,logTotals=forward_observalbe_tensor_moments([T0,Y0],layers,checkerboard=checkerboard,return_layers=True,cached_Ts=Ts)
_=[(trace_two_tensors(Y).item(),trace_two_tensors(T).item()) for T,Y in T_op_momentss[:]]
[((_[0]/_[1] if _[1]!=0 else 0),_[1]) for _ in _]

In [4]:
scdimss=[get_scdims(T,n=(1,1),k=5)[0] for T in Ts[::3]]
scdimss

0it [00:00, ?it/s]

0it [00:00, ?it/s]

0it [00:00, ?it/s]

0it [00:00, ?it/s]

0it [00:00, ?it/s]

0it [00:00, ?it/s]

[tensor([0.0000, 0.1497]),
 tensor([0.0000, 0.1050, 0.1050, 0.1331, 0.2980]),
 tensor([0.0000, 0.0371, 0.0371, 0.0632, 0.1074]),
 tensor([0.0000, 0.0027, 0.0165, 0.0165, 0.0181]),
 tensor([0.0000, 0.0116, 0.0136, 0.0136, 0.0136]),
 tensor([0.0000, 0.0024, 0.0024, 0.0025, 0.0025])]

tensor([0.0000, 0.1497])